
# This file is autogenerated - do not edit it

def conversation(person, people):
    """The conversation"""
    
    if person == 'Fred' and people['Fred'].get('general-question', False):
        yield 'Did you have any other questions?'
        while True:
            result = (yield "Is there a way out?", "Is there anything to do?", "I have nothing further")
            if result == "Is there a way out?":
                yield 'No'
            elif result == "Is there anything to do?":
                yield 'Lots'
            elif result == "I have nothing further":
                yield 'Fine'
                break

    elif person == 'Fred' and people['Bob'].get('spoken-once', False):
        yield 'So Bob filled you in?'
        result = (yield "Yes", "No")
        if result == "Yes":
            yield 'Ok, well then. You should know it all'
            people['Fred']['general-question'] = True
            raise StopIteration(1)
        elif result == "No":
            yield 'Well, go and talk to him again'
            people['Bob']['spoken-once'] = False
            people['Bob']['spoken-twice'] = False

    elif person == 'Fred' and people['Fred'].get('failed-once', False):
        yield 'I told you before and I won\'t tell you again. Talk to Bob!'
        yield 'Duly noted.'

    elif person == 'Bob' and people['Bob'].get('spoken-twice', False):
        yield 'Well, you are the chatty one aren\'t you?'

    elif person == 'Bob' and people['Bob'].get('spoken-once', False):
        yield 'Hello again'
        yield 'Bye'
        people['Bob']['spoken-twice'] = True

    elif person == 'Fred':
        yield 'You need to talk to Bob first'
        yield 'Ok, I will'
        people['Fred']['failed-once'] = True

    elif person == 'Bob':
        yield 'Hello, we haven\'t seen each other before'
        yield 'No, this is the first time'
        yield 'Well hello, and welcome to the town'
        result = (yield "Thanks", "The town?")
        if result == "Thanks":
            yield 'You are welcome. Please feel free to ask me anything'
        elif result == "The town?":
            yield 'Yes, you are in a town you know. Got any questions?'
        while True:
            result = (yield "Where is the cathedral?", "Is there a shop here?", "I've nothing more to ask")
            if result == "Where is the cathedral?":
                yield 'Yes, it is in the north'
            elif result == "Is there a shop here?":
                yield 'What kind of shop did you have in mind?'
                result = (yield "A health shop", "A bomb shop")
                if result == "A health shop":
                    yield 'Well, that is to the east'
                elif result == "A bomb shop":
                    yield 'There isn\'t one of those'
            elif result == "I\'ve nothing more to ask":
                break
        people['Bob']['spoken-once'] = True

